name: CI/CD Auto-Deploy @ Saji-LeoScientific

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: Ubuntu
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
  
    - name: Installation
      run: yarn
#       run: npm i
    - name: Latest Version of Docusaurus Installation  !!
      run:  yarn @docusaurus/core@latest @docusaurus/preset-classic@latest
    - name: Check and Update Packages !!
      run: yarn upgrade   
    - name: Docusaurus 2 Building Process
      run: yarn build
#       run: npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: ./website/build
        publish_dir: ./build/
